//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Razor_Empty {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlCmd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlCmd() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_Razor_Empty.SqlCmd", typeof(SqlCmd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 學生成績報告_國中,學生成績報告_高中,學生成績報告_各縣市鄉鎮區市報表,學生成績報告_縣市國中等級分布,各科通過率分析_國中,各科通過率分析_高中,分項能力分析_國中,
        ///分項能力分析_高中,分項能力分析_縣市,各科通過率分析_國中版(各縣市),各科通過率分析_高中版(教育單位) 的當地語系化字串。
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT [Administrator] as CityName FROM [Administration_SchoolCode] group by [Administrator] 的當地語系化字串。
        /// </summary>
        internal static string Select_Administrator {
            get {
                return ResourceManager.GetString("Select_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT CityName  FROM [JuniorSchoolZipCode] group by CityName order by CityName 的當地語系化字串。
        /// </summary>
        internal static string Select_CityName {
            get {
                return ResourceManager.GetString("Select_CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT US_ID FROM [USERS] where US_ID=&apos;{0}&apos; and US_PW=&apos;{1}&apos; 的當地語系化字串。
        /// </summary>
        internal static string Select_IDandPW {
            get {
                return ResourceManager.GetString("Select_IDandPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT * FROM [RankDistribution_Junior_Table] where TestYear=&apos;{0}&apos; and SchoolCode=&apos;{1}&apos; 的當地語系化字串。
        /// </summary>
        internal static string Select_Junior {
            get {
                return ResourceManager.GetString("Select_Junior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT Rtrim([SchoolCode])+&apos;,&apos;+Rtrim([SchoolName]) as SchoolName FROM [JuniorSchoolZipCode]  where [SchoolCode] in (select [SchoolCode] from SchoolCodeAnalysis where TestYear=&apos;{0}&apos; and  CityName=&apos;{1}&apos;) 的當地語系化字串。
        /// </summary>
        internal static string Select_JuniorSchoolName {
            get {
                return ResourceManager.GetString("Select_JuniorSchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT * FROM  [RankDistribution_Senior_Table]  where TestYear=&apos;{0}&apos; and  SchoolCode=&apos;{1}&apos; and DeptCode=&apos;{2}&apos; 的當地語系化字串。
        /// </summary>
        internal static string Select_Senior {
            get {
                return ResourceManager.GetString("Select_Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT AdsDep.CombineName as SchoolCode,(Rtrim(AdS.[SchoolName])+&apos;,&apos;+AdsDep.CombineName) as SchoolName FROM [Administration_SchoolCode] AdS left join (SELECT [ADMSchoolCode],  [DeptCode] , Rtrim([ADMSchoolCode])+&apos;_&apos;+Rtrim([DeptCode]) as CombineName FROM [SeniorStudentData] where TestYear=&apos;{0}&apos; group by [ADMSchoolCode],[DeptCode]) AdsDep on AdS.[SchoolCode]=AdsDep.ADMSchoolCode where Ads.Administrator=&apos;五專&apos; and AdsDep.CombineName is not null order by AdS.[SchoolCode] 的當地語系化字串。
        /// </summary>
        internal static string Select_SeniorSchoolName {
            get {
                return ResourceManager.GetString("Select_SeniorSchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT [ItemNo],[ReportKind],[RptFileName],[RptFilePath],[RptVariables],[RptVariablesName],[OutPutPath],[OutPutFileName],[SPName_Query],[SPName_QueryCSV],[PDFFile],[CSVFile],[Check_Data_SP],[Check_Data_SP_Variable] FROM [RankDistribution].[dbo].[Setting] 的當地語系化字串。
        /// </summary>
        internal static string Select_Setting {
            get {
                return ResourceManager.GetString("Select_Setting", resourceCulture);
            }
        }
    }
}
